ESPECIES_INSS_MAP = {
    "01": "Pensão por morte do trabalhador rural",
    "02": "Pensão por morte por acidente do trabalho do trabalhador rural",
    "03": "Pensão por morte de ex-combatente",
    "04": "Aposentadoria por invalidez do trabalhador rural",
    "05": "Aposentadoria por invalidez por acidente do trabalho do trabalhador rural",
    "06": "Aposentadoria por invalidez de ex-combatente",
    "07": "Aposentadoria por idade do trabalhador rural",
    "08": "Aposentadoria por idade de ex-combatente",
    "09": "Pensão por morte de ex-combatente",
    "10": "Pensão por morte por acidente do trabalho de ex-combatente",
    "11": "Aposentadoria por invalidez",
    "12": "Aposentadoria por invalidez por acidente do trabalho",
    "13": "Pensão por morte",
    "14": "Pensão por morte por acidente do trabalho",
    "15": "Pensão por morte do trabalhador rural",
    "16": "Aposentadoria por invalidez do trabalhador rural",
    "17": "Aposentadoria por idade do trabalhador rural",
    "18": "Auxílio-acidente do trabalhador rural",
    "19": "Pensão de estudante",
    "20": "Pensão por morte de diplomata",
    "21": "Pensão por morte previdenciária",
    "22": "Pensão por morte estatutária",
    "23": "Pensão por morte de ex-combatente",
    "24": "Pensão especial",
    "25": "Auxílio-reclusão do trabalhador rural",
    "26": "Pensão por morte",
    "27": "Pensão por morte de servidor público federal com dupla aposentadoria",
    "28": "Pensão por morte do Regime Geral",
    "29": "Pensão por morte de ex-combatente marítimo",
    "30": "Renda mensal vitalícia por invalidez",
    "31": "Auxílio-doença previdenciário",
    "32": "Aposentadoria por invalidez previdenciária",
    "33": "Aposentadoria por invalidez de aeronauta",
    "34": "Aposentadoria por invalidez de ex-combatente marítimo",
    "35": "Auxílio-doença do trabalhador rural",
    "36": "Aposentadoria por invalidez",
    "37": "Aposentadoria de extrativista",
    "38": "Aposentadoria de extrativista por invalidez",
    "39": "Pensão por morte de extrativista",
    "40": "Renda mensal vitalícia por idade",
    "41": "Aposentadoria por idade previdenciária",
    "42": "Aposentadoria por tempo de contribuição previdenciária",
    "43": "Aposentadoria por tempo de contribuição de ex-combatente",
    "44": "Aposentadoria por tempo de contribuição de aeronauta",
    "45": "Aposentadoria por tempo de contribuição de jornalista",
    "46": "Aposentadoria por tempo de contribuição especial",
    "47": "Aposentadoria por tempo de contribuição ordinária",
    "48": "Aposentadoria por tempo de contribuição de professor",
    "49": "Aposentadoria por tempo de contribuição de anistiado",
    "50": "Pensão por morte de ex-combatente",
    "51": "Aposentadoria por invalidez",
    "52": "Aposentadoria por idade",
    "53": "Aposentadoria por tempo de contribuição de anistiado",
    "54": "Pensão especial vitalícia (Lei nº 9.796/1999)",
    "55": "Pensão por morte",
    "56": "Pensão vitalícia",
    "57": "Aposentadoria por tempo de contribuição de professor",
    "58": "Aposentadoria por tempo de contribuição",
    "59": "Pensão por morte",
    "60": "Aposentadoria por invalidez",
    "61": "Aposentadoria por idade",
    "62": "Aposentadoria por tempo de contribuição",
    "63": "Pensão por morte",
    "64": "Aposentadoria por invalidez",
    "65": "Aposentadoria por idade",
    "66": "Aposentadoria por tempo de contribuição",
    "67": "Pensão por morte",
    "68": "Aposentadoria por invalidez",
    "69": "Aposentadoria por idade",
    "70": "Aposentadoria por tempo de contribuição",
    "71": "Pensão por morte",
    "72": "Aposentadoria por tempo de contribuição de ex-combatente",
    "73": "Aposentadoria por tempo de contribuição de aeronáuta",
    "74": "Aposentadoria por tempo de contribuição de jornalista",
    "75": "Aposentadoria por tempo de contribuição especial",
    "76": "Aposentadoria por tempo de contribuição",
    "77": "Pensão por morte de ex-combatente",
    "78": "Aposentadoria por idade",
    "79": "Aposentadoria por tempo de contribuição",
    "80": "Pensão por morte",
    "81": "Aposentadoria por idade",
    "82": "Aposentadoria por tempo de contribuição",
    "83": "Pensão por morte",
    "84": "Aposentadoria por invalidez",
    "85": "Aposentadoria por idade",
    "86": "Aposentadoria por tempo de contribuição",
    "87": "Pensão por morte",
    "88": "Amparo social ao idoso (LOAS)",
    "89": "Pensão especial de anistiado",
    "90": "Aposentadoria por invalidez",
    "91": "Auxílio-doença por acidente do trabalho",
    "92": "Aposentadoria por invalidez por acidente do trabalho",
    "93": "Pensão por morte por acidente do trabalho",
    "94": "Auxílio-acidente por acidente do trabalho",
    "95": "Auxílio-suplementar por acidente do trabalho",
    "96": "Pensão especial",
    "97": "Pensão vitalícia",
    "98": "Pensão vitalícia",
    "99": "Pensão vitalícia"
}
