FROM node:20-alpine

WORKDIR /app

COPY ./frontend/package*.json ./

RUN npm install
RUN npm rebuild

COPY ./frontend ./

ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
# Limita o uso de memória do Node durante o build para evitar o erro 'Killed'
ENV NODE_OPTIONS="--max-old-space-size=1024"
RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]
