FROM node:20-alpine

WORKDIR /app

# Limita o uso de memória do Node para evitar o erro 'Killed'
ENV NODE_OPTIONS="--max-old-space-size=1536"

COPY ./frontend/package*.json ./

# Instalação com flags para economizar memória e ignorar a falta de lockfile
RUN npm install --no-audit --no-fund --loglevel=error

COPY ./frontend ./

ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]
